info:
  name: Update My Settings
  type: http
  seq: 4

http:
  method: PATCH
  url: "{{backoffice-api-url}}/users/me/settings"
  body:
    type: json
    json: |
      {
        "locale": "en-US",
        "timezone": "America/Sao_Paulo"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
