info:
  name: Create From Config
  type: http
  seq: 13

http:
  method: POST
  url: "{{msgops-api-url}}/campaigns/from-config/1"
  body:
    type: json
    json: |
      {
        "title": "Campaign From Config",
        "name": "config-campaign"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
