syntax = "proto3";

package geoip;

service GeoIpService {
  rpc GetLocation (IpRequest) returns (LocationResponse) {}
}

message IpRequest {
  string ip = 1; // Can be IPv4 or IPv6
}

message LocationResponse {
  string country = 1; // ISO code
  string region = 2;  // ISO code
  string city = 3;
  string postalCode = 4;
  string timezone = 5;
  double latitude = 6;
  double longitude = 7;
  bool success = 8;   // To indicate if lookup was successful
  string error = 9;   // Error message if any
}
