# 1
# Precisamos enviar para o lead conception o lead com o workflow configurado na variavel FEATURE_EMAIL_PULL_SENDER

POST https://msgops-lead-conception-p6tcfyf7qa-ue.a.run.app/workflow
content-type: application/json

{
  "contact": {
    "email": "jonathan.shun+f01@brius.com.br",
    "phone": "31973650997",
    "hashedEmail": "ea280c2cde52357cc43ff6ce73571defdeefb351dce5456ea20ef6c5ec5e0e40",
    "firstName": "JonathanF01",
    "lastName": "Shun",
    "audienceName": "shun_teste_feature_pull",
    "audienceUrl": "shun_teste_feature_pull"
  },
  "tagId": "shun_teste_feature_pull",
  "startDate": 1645024532553
} 


# Depois disso deve ser executado no lead-conception e enviado para o message-trigger
# Neste momento o message-trigger deve ativar a feature é mandar o email para a fila 
# TOPIC_FEATURE_EMAIL_PULL_SENDER

# 2 - Ver a fila
# Acessar - https://console.cloud.google.com/cloudpubsub/subscription/detail/msgops.send.email.feature.pull-sender-sub?project=etus-media-development-staging&tab=overview

### 

# 3 { LOCAL } - Consumir as mensagens na fila  

POST http://localhost:3000/consume-email?debug=true
content-type: application/json

{
  
}

# 3 { STAGING } - Consumir as mensagens na fila  

POST https://msgops-campaign-trigger-p6tcfyf7qa-ue.a.run.app/consume-email
content-type: application/json

{
  
}
