info:
  name: Create Automation
  type: http
  seq: 4

http:
  method: POST
  url: "{{msgops-api-url}}/automations/complete"
  body:
    type: json
    json: |
      {
        "title": "Test Automation",
        "description": "Test description",
        "name": "test-automation",
        "isActive": false,
        "type": "email",
        "steps": [],
        "triggers": []
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
