info:
  name: Update Automation
  type: http
  seq: 5

http:
  method: PUT
  url: '{{msgops-api-url}}/automations/complete'
  body:
    type: json
    json: |
      {
        "id": 1,
        "title": "Updated Automation",
        "description": "Updated description",
        "name": "test-automation",
        "isActive": true,
        "type": "email",
        "steps": [],
        "triggers": []
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
