import { mkdirSync, writeFileSync } from 'fs';
import { dirname } from 'path';
import type { GeoIpSettingsDto } from '../modules/setup/dtos/geoip-settings.dto';
import { bmsConfigFilePath } from './bms-config-paths';

export function geoIpEnvFilePath(): string {
  return bmsConfigFilePath('geoip.env');
}

// Maps a persisted GeoIpSettingsDto to the env vars consumed by
// download-geodb.sh and apps/geolocation. Idempotent — safe to call on
// every save and on msgops-api startup if the file is missing.
export function writeGeoIpEnvFile(dto: GeoIpSettingsDto): void {
  const lines: string[] = ['# Generated by BMS. Do not edit manually — overwritten on each save.', ''];

  if (dto.mode === 'disabled') {
    lines.push('GEO_TIER=disabled');
  } else if (dto.mode === 'lite') {
    lines.push('GEO_TIER=lite');
  } else {
    switch (dto.provider) {
      case 'dbip-full':
        lines.push('GEO_TIER=full');
        if (dto.apiKey) lines.push(`DBIP_API_KEY=${dto.apiKey}`);
        break;
      case 'maxmind':
        lines.push('GEO_TIER=maxmind');
        if (dto.accountId) lines.push(`MAXMIND_ACCOUNT_ID=${dto.accountId}`);
        if (dto.licenseKey) lines.push(`MAXMIND_LICENSE_KEY=${dto.licenseKey}`);
        break;
      case 'ip-api':
        lines.push('GEO_TIER=api');
        lines.push('GEO_API_VENDOR=ip-api');
        if (dto.apiKey) lines.push(`GEO_API_KEY=${dto.apiKey}`);
        break;
      case 'ipinfo':
        lines.push('GEO_TIER=api');
        lines.push('GEO_API_VENDOR=ipinfo');
        if (dto.apiKey) lines.push(`GEO_API_KEY=${dto.apiKey}`);
        break;
    }
  }

  const filePath = geoIpEnvFilePath();
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, lines.join('\n') + '\n', 'utf8');
}

export function maskCredential(value: string | undefined): string | undefined {
  if (!value) return undefined;
  if (value.length <= 8) return '***';
  return value.slice(0, 3) + '***' + value.slice(-3);
}
