import { mkdirSync, writeFileSync } from 'fs';
import { dirname } from 'path';
import { bmsConfigFilePath } from './bms-config-paths';

const HEADER = '# Generated by BMS. Do not edit manually — overwritten on each save.';

function writeEnvFile(path: string, lines: string[]): void {
  mkdirSync(dirname(path), { recursive: true });
  const content = [HEADER, '', ...lines].join('\n') + '\n';
  writeFileSync(path, content, 'utf8');
}

// ---------- S3 ----------

export interface S3SystemSettings {
  endpoint?: string;
  region?: string;
  bucket: string;
  accessKeyId: string;
  secretAccessKey: string;
  useObjectAcls?: boolean;
  assetsUrl?: string;
}

export function s3EnvFilePath(): string {
  return bmsConfigFilePath('s3.env');
}

export function writeS3EnvFile(dto: S3SystemSettings): void {
  const lines: string[] = [];
  if (dto.endpoint) lines.push(`S3_ENDPOINT=${dto.endpoint}`);
  if (dto.region) lines.push(`S3_REGION=${dto.region}`);
  lines.push(`S3_BUCKET=${dto.bucket}`);
  lines.push(`S3_ACCESS_KEY_ID=${dto.accessKeyId}`);
  lines.push(`S3_SECRET_ACCESS_KEY=${dto.secretAccessKey}`);
  if (dto.useObjectAcls === false) lines.push('S3_USE_OBJECT_ACLS=false');
  if (dto.assetsUrl) lines.push(`BMS_ASSETS_URL=${dto.assetsUrl}`);
  writeEnvFile(s3EnvFilePath(), lines);
}

// ---------- SendGrid (system-level) ----------

export interface SendgridSystemSettings {
  apiKey: string;
  apiBaseUrl?: string;
  webhookUrlBase?: string;
  ipPool?: string;
}

export function sendgridEnvFilePath(): string {
  return bmsConfigFilePath('sendgrid.env');
}

export function writeSendgridEnvFile(dto: SendgridSystemSettings): void {
  const lines: string[] = [`SENDGRID_API_KEY=${dto.apiKey}`];
  if (dto.apiBaseUrl) lines.push(`SENDGRID_API_BASE_URL=${dto.apiBaseUrl}`);
  if (dto.webhookUrlBase) lines.push(`SENDGRID_WEBHOOK_URL_BASE=${dto.webhookUrlBase}`);
  if (dto.ipPool) lines.push(`SENDGRID_IP_POOL=${dto.ipPool}`);
  writeEnvFile(sendgridEnvFilePath(), lines);
}

// ---------- FCM ----------

export interface FcmSystemSettings {
  // Raw Google service-account JSON. Stored in DB as a structured value but
  // serialized to a single line in the env file so workers can parse it back.
  serviceAccountJson: string;
}

export function fcmEnvFilePath(): string {
  return bmsConfigFilePath('fcm.env');
}

export function writeFcmEnvFile(dto: FcmSystemSettings): void {
  // Validate JSON is parseable; throw early so we never write a corrupt env file.
  JSON.parse(dto.serviceAccountJson);
  // Collapse to single line (the file format is line-based; \n inside the
  // private_key is preserved as an escaped \n inside the JSON string).
  const oneLine = JSON.stringify(JSON.parse(dto.serviceAccountJson));
  writeEnvFile(fcmEnvFilePath(), [`FIREBASE_SERVICE_ACCOUNT=${oneLine}`]);
}

// ---------- MailerSend ----------

export interface MailerSendSystemSettings {
  apiKey: string;
  webhookSigningSecret?: string;
  webhookUrlBase?: string;
}

export function mailerSendEnvFilePath(): string {
  return bmsConfigFilePath('mailersend.env');
}

export function writeMailerSendEnvFile(dto: MailerSendSystemSettings): void {
  const lines: string[] = [`MAILERSEND_API_KEY=${dto.apiKey}`];
  if (dto.webhookSigningSecret) lines.push(`MAILERSEND_WEBHOOK_SIGNING_SECRET=${dto.webhookSigningSecret}`);
  if (dto.webhookUrlBase) lines.push(`MAILERSEND_WEBHOOK_URL_BASE=${dto.webhookUrlBase}`);
  writeEnvFile(mailerSendEnvFilePath(), lines);
}

// ---------- Resend ----------

export interface ResendSystemSettings {
  apiKey: string;
  webhookSigningSecret?: string;
  webhookUrlBase?: string;
}

export function resendEnvFilePath(): string {
  return bmsConfigFilePath('resend.env');
}

export function writeResendEnvFile(dto: ResendSystemSettings): void {
  const lines: string[] = [`RESEND_API_KEY=${dto.apiKey}`];
  if (dto.webhookSigningSecret) lines.push(`RESEND_WEBHOOK_SIGNING_SECRET=${dto.webhookSigningSecret}`);
  if (dto.webhookUrlBase) lines.push(`RESEND_WEBHOOK_URL_BASE=${dto.webhookUrlBase}`);
  writeEnvFile(resendEnvFilePath(), lines);
}

// ---------- Amazon SES ----------

export interface SesSystemSettings {
  accessKeyId: string;
  secretAccessKey: string;
  region: string;
  webhookSnsTopicArn?: string;
}

export function sesEnvFilePath(): string {
  return bmsConfigFilePath('ses.env');
}

export function writeSesEnvFile(dto: SesSystemSettings): void {
  const lines: string[] = [`AWS_SES_ACCESS_KEY_ID=${dto.accessKeyId}`, `AWS_SES_SECRET_ACCESS_KEY=${dto.secretAccessKey}`, `AWS_SES_REGION=${dto.region}`];
  if (dto.webhookSnsTopicArn) lines.push(`AWS_SES_WEBHOOK_SNS_TOPIC_ARN=${dto.webhookSnsTopicArn}`);
  writeEnvFile(sesEnvFilePath(), lines);
}

// ---------- Mandrill ----------

export interface MandrillSystemSettings {
  apiKey: string;
  webhookKey?: string;
  webhookUrlBase?: string;
}

export function mandrillEnvFilePath(): string {
  return bmsConfigFilePath('mandrill.env');
}

export function writeMandrillEnvFile(dto: MandrillSystemSettings): void {
  const lines: string[] = [`MANDRILL_API_KEY=${dto.apiKey}`];
  if (dto.webhookKey) lines.push(`MANDRILL_WEBHOOK_KEY=${dto.webhookKey}`);
  if (dto.webhookUrlBase) lines.push(`MANDRILL_WEBHOOK_URL_BASE=${dto.webhookUrlBase}`);
  writeEnvFile(mandrillEnvFilePath(), lines);
}

// ---------- WhatsApp Meta (Cloud API direct mode) ----------

export interface WhatsappMetaSystemSettings {
  appId: string;
  appSecret: string;
  configId: string;
  verifyToken: string;
  graphVersion?: string;
}

export function whatsappMetaEnvFilePath(): string {
  return bmsConfigFilePath('whatsapp-meta.env');
}

export function writeWhatsappMetaEnvFile(dto: WhatsappMetaSystemSettings): void {
  const lines: string[] = [
    `WHATSAPP_APP_ID=${dto.appId}`,
    `WHATSAPP_APP_SECRET=${dto.appSecret}`,
    `WHATSAPP_CONFIG_ID=${dto.configId}`,
    `WHATSAPP_VERIFY_TOKEN=${dto.verifyToken}`,
  ];
  if (dto.graphVersion) lines.push(`WHATSAPP_GRAPH_VERSION=${dto.graphVersion}`);
  writeEnvFile(whatsappMetaEnvFilePath(), lines);
}

// ---------- WhatsApp EvoHub (turnkey mode) ----------
//
// Base URL is fixed at https://api.evohub.ai — same convention as the CRM
// (HUB_API_URL constant in evo-ai-crm-community/lib/meta_base_url.rb). Not
// exposed in the admin UI. The EVOLUTION_HUB_URL env var stays available as
// an emergency override for dev / staging Hub mocks but is never written by
// the admin save flow.

export interface WhatsappHubSystemSettings {
  enabled: boolean;
  apiKey: string;
  webhookSecret: string;
}

export function whatsappHubEnvFilePath(): string {
  return bmsConfigFilePath('whatsapp-hub.env');
}

export function writeWhatsappHubEnvFile(dto: WhatsappHubSystemSettings): void {
  const lines: string[] = [`EVOLUTION_HUB_ENABLED=${dto.enabled ? 'true' : 'false'}`, `EVOLUTION_HUB_API_KEY=${dto.apiKey}`, `EVOLUTION_HUB_WEBHOOK_SECRET=${dto.webhookSecret}`];
  writeEnvFile(whatsappHubEnvFilePath(), lines);
}
