import { mkdtempSync, readFileSync, rmSync, existsSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import {
  s3EnvFilePath,
  sendgridEnvFilePath,
  fcmEnvFilePath,
  emailableEnvFilePath,
  writeS3EnvFile,
  writeSendgridEnvFile,
  writeFcmEnvFile,
  writeEmailableEnvFile,
} from './integrations-config-file';

let tmp: string;

beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), 'bms-integrations-'));
  process.env.BMS_CONFIG_DIR = tmp;
});

afterEach(() => {
  rmSync(tmp, { recursive: true, force: true });
  delete process.env.BMS_CONFIG_DIR;
});

describe('integrations-config-file', () => {
  it('writeS3EnvFile produces idempotent content', () => {
    writeS3EnvFile({
      bucket: 'acme',
      accessKeyId: 'AKIAACME',
      secretAccessKey: 'shhh',
      region: 'us-east-1',
      endpoint: 'http://minio:9000',
      useObjectAcls: false,
      assetsUrl: 'cdn.example.com',
    });
    const first = readFileSync(s3EnvFilePath(), 'utf8');

    writeS3EnvFile({
      bucket: 'acme',
      accessKeyId: 'AKIAACME',
      secretAccessKey: 'shhh',
      region: 'us-east-1',
      endpoint: 'http://minio:9000',
      useObjectAcls: false,
      assetsUrl: 'cdn.example.com',
    });
    const second = readFileSync(s3EnvFilePath(), 'utf8');

    expect(first).toBe(second);
    expect(first).toMatch(/^# Generated by BMS/);
    expect(first).toContain('S3_BUCKET=acme');
    expect(first).toContain('S3_USE_OBJECT_ACLS=false');
  });

  it('writeSendgridEnvFile writes only present fields', () => {
    writeSendgridEnvFile({ apiKey: 'SG.test', apiBaseUrl: 'http://mock' });
    const content = readFileSync(sendgridEnvFilePath(), 'utf8');
    expect(content).toContain('SENDGRID_API_KEY=SG.test');
    expect(content).toContain('SENDGRID_API_BASE_URL=http://mock');
    expect(content).not.toContain('SENDGRID_IP_POOL=');
  });

  it('writeFcmEnvFile collapses JSON to single line', () => {
    const json = JSON.stringify({
      type: 'service_account',
      project_id: 'p',
      private_key: '-----\nKEY\n-----',
      client_email: 'a@b.iam',
    });
    writeFcmEnvFile({ serviceAccountJson: json });
    const content = readFileSync(fcmEnvFilePath(), 'utf8');
    const lines = content.trim().split('\n');
    const fcmLine = lines.find((l) => l.startsWith('FIREBASE_SERVICE_ACCOUNT='));
    expect(fcmLine).toBeDefined();
    expect(fcmLine!.split('\n')).toHaveLength(1);
  });

  it('writeFcmEnvFile rejects malformed JSON', () => {
    expect(() => writeFcmEnvFile({ serviceAccountJson: '{not json' })).toThrow();
  });

  it('writeEmailableEnvFile writes both fields', () => {
    writeEmailableEnvFile({ url: 'https://api.emailable.com/v1/verify', apiKey: 'em-test-key' });
    const content = readFileSync(emailableEnvFilePath(), 'utf8');
    expect(content).toContain('EMAILABLE_URL=https://api.emailable.com/v1/verify');
    expect(content).toContain('EMAILABLE_API_KEY=em-test-key');
  });

  it('all paths use BMS_CONFIG_DIR', () => {
    expect(s3EnvFilePath().startsWith(tmp)).toBe(true);
    expect(sendgridEnvFilePath().startsWith(tmp)).toBe(true);
    expect(fcmEnvFilePath().startsWith(tmp)).toBe(true);
    expect(emailableEnvFilePath().startsWith(tmp)).toBe(true);
    expect(existsSync(tmp)).toBe(true);
  });
});
