export const PUBLIC_ROUTE_KEY = 'isPublicRoute';
export const CRON_ROUTE_KEY = 'isCronRoute';
export const REQUIRED_PERMISSIONS_KEY = 'requiredPermissions';
export const REQUIRE_SUPER_ADMIN_KEY = 'requireSuperAdmin';

export const ROLE_CODES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  EDITOR: 'editor',
  ANALYST: 'analyst',
  SUPPORT: 'support',
  BILLING: 'billing',
} as const;

export const ALL_PERMISSION_KEYS = [
  'campaigns:view',
  'campaigns:create',
  'campaigns:create_from_rule',
  'campaigns:update',
  'campaigns:delete',
  'campaigns:send',
  'campaigns:schedule',
  'campaigns:pause',
  'campaigns:resume',
  'campaigns:cancel',
  'campaigns:duplicate',
  'automations:view',
  'automations:create',
  'automations:update',
  'automations:delete',
  'automations:activate',
  'automations:deactivate',
  'automations:test',
  'messages:view',
  'messages:create',
  'messages:update',
  'messages:delete',
  'messages:test_send',
  'audience:contacts_view',
  'audience:contacts_edit',
  'audience:contacts_import',
  'audience:contacts_export',
  'audience:contacts_suppress',
  'audience:segments_view',
  'audience:segments_execute',
  'audience:tags_view',
  'audience:tags_manage',
  'audience:custom_fields_view',
  'audience:custom_fields_manage',
  'infra:pools_read',
  'infra:labels_read',
  'infra:campaign_rules_read',
  'infra:view',
  'infra:manage',
  'analytics:dashboard_view',
  'analytics:dashboard_export',
  'analytics:insights_view',
  'analytics:comparison_view',
  'account:settings_view',
  'account:settings_update',
  'account:users_view',
  'account:users_invite',
  'account:users_update_roles',
  'account:roles_view',
  'account:api_keys_view',
  'account:api_keys_create',
  'account:api_keys_rotate',
  'account:api_keys_revoke',
  'account:api_keys_update_role',
  'audit_logs:view',
  'audit_logs:export',
] as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  [ROLE_CODES.SUPER_ADMIN]: [...ALL_PERMISSION_KEYS],
  [ROLE_CODES.ADMIN]: [...ALL_PERMISSION_KEYS],
  [ROLE_CODES.EDITOR]: [
    'campaigns:view',
    'campaigns:create',
    'campaigns:create_from_rule',
    'campaigns:update',
    'campaigns:delete',
    'campaigns:send',
    'campaigns:schedule',
    'campaigns:pause',
    'campaigns:resume',
    'campaigns:cancel',
    'campaigns:duplicate',
    'automations:view',
    'automations:create',
    'automations:update',
    'automations:delete',
    'automations:activate',
    'automations:deactivate',
    'automations:test',
    'messages:view',
    'messages:create',
    'messages:update',
    'messages:delete',
    'messages:test_send',
    'audience:contacts_view',
    'audience:contacts_edit',
    'audience:tags_view',
    'audience:custom_fields_view',
    'infra:pools_read',
    'infra:labels_read',
    'infra:campaign_rules_read',
    'analytics:dashboard_view',
    'analytics:insights_view',
    'analytics:comparison_view',
  ],
  [ROLE_CODES.ANALYST]: [
    'campaigns:view',
    'automations:view',
    'messages:view',
    'audience:contacts_view',
    'audience:segments_view',
    'audience:tags_view',
    'audience:custom_fields_view',
    'analytics:dashboard_view',
    'analytics:insights_view',
    'analytics:comparison_view',
    'account:settings_view',
    'account:users_view',
    'account:roles_view',
  ],
  [ROLE_CODES.SUPPORT]: ['audience:contacts_view', 'audience:contacts_edit', 'audience:contacts_suppress', 'analytics:dashboard_view'],
  [ROLE_CODES.BILLING]: [],
};

export const SYSTEM_ROLES_SEED = [
  { code: ROLE_CODES.SUPER_ADMIN, name: 'Super Admin', description: 'Acesso total plataforma', isSystem: true },
  { code: ROLE_CODES.ADMIN, name: 'Admin', description: 'Acesso total na conta', isSystem: true },
  { code: ROLE_CODES.EDITOR, name: 'Editor', description: 'Operacao de engajamento', isSystem: true },
  { code: ROLE_CODES.ANALYST, name: 'Analyst', description: 'Leitura ampla', isSystem: true },
  { code: ROLE_CODES.SUPPORT, name: 'Support', description: 'Gestao de contatos e suppressions', isSystem: true },
  { code: ROLE_CODES.BILLING, name: 'Billing', description: 'Gestao de custos e invoices', isSystem: true },
];
