version: '3.8'

services:
  msgops:
    image: msgops-event-process:local
    networks:
      - network
    environment:
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      DATABASE_HOST: 'db'
      DATABASE_PORT: '5432'
      DATABASE_DATABASE: 'msgops'
      DATABASE_USERNAME: 'user'
      DATABASE_PASSWORD: 123456
      KAFKA_BROKERS: 'kafka:9092'
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
      - kafka
  db:
    image: postgres:latest
    networks:
      - network
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: 'user'
      POSTGRES_DB: 'msgops'
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - network
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    networks:
      - network
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'
    volumes:
      - kafka-data:/var/lib/kafka/data

networks:
  network:

volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
