info:
  name: Create Config
  type: http
  seq: 10

http:
  method: POST
  url: "{{msgops-api-url}}/campaigns-rules/configs"
  body:
    type: json
    json: |
      {
        "name": "Test Config",
        "description": "Test config description"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
