info:
  name: Delete Config
  type: http
  seq: 12

http:
  method: DELETE
  url: "{{msgops-api-url}}/campaigns-rules/configs/1"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
