info:
  name: Update Config
  type: http
  seq: 11

http:
  method: PUT
  url: '{{msgops-api-url}}/campaigns-rules/configs/1'
  body:
    type: json
    json: |
      {
        "name": "Updated Config"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
