export class ContactsDto {
  id?: number;
  name?: string;
  email?: string;
  emailProvider?: string;
  firstName?: string;
  lastName?: string;
  hashedEmail?: string;
  phone?: string;
  isActive?: boolean;
  isUnsubscribed?: number;
  isValid?: number;
  hasBounced?: number;
  hasEmail?: number;
  hasPhone?: number;
  hasWebPush?: number;
  hasMobilePush?: number;
  hasWhatsapp?: number;
  lastSent?: string;
  lastSentDate?: string;
  lastOpen?: string;
  lastOpenDate?: string;
  lastClick?: string;
  lastClickDate?: string;
  lastAutomation?: string;
  lastAutomationDate?: string;
  sendingLimit?: number;
  customFields?: Array<object>;
  score?: number;
  scoreForecast?: number;
  createdAt?: Date;
  updatedAt?: Date;
  webPushLastSent?: Date;
  webPushLastClick?: Date;
  webPushLastOpen?: Date;
  webPushLastDelivered?: Date;
  smsLastSent?: Date;
  smsLastClick?: Date;
  smsLastOpen?: Date;
  smsLastDelivered?: Date;
  whatsappLastClick?: Date;
  whatsappLastSent?: Date;
  whatsappLastOpen?: Date;
  whatsappLastDelivered?: Date;
  mobPushLastClick?: Date;
  mobPushLastSent?: Date;
  mobPushLastOpen?: Date;
  mobPushLastDelivered?: Date;
  contactTag?: string[];
  postal: number;
  city: string;
  region: string;
  country: string;
  webPush: string;
  isBlocked?: boolean;

  constructor(contactsDto: ContactsDto = {} as ContactsDto) {
    this.id = contactsDto.id;
    this.name = contactsDto.name;
    this.email = contactsDto.email;
    this.emailProvider = contactsDto.emailProvider;
    this.firstName = contactsDto.firstName;
    this.lastName = contactsDto.lastName;
    this.hashedEmail = contactsDto.hashedEmail;
    this.phone = contactsDto.phone;
    this.isActive = contactsDto.isActive;
    this.isUnsubscribed = contactsDto.isUnsubscribed;
    this.isValid = contactsDto.isValid;
    this.hasBounced = contactsDto.hasBounced;
    this.hasEmail = contactsDto.hasEmail;
    this.hasPhone = contactsDto.hasPhone;
    this.hasWebPush = contactsDto.hasWebPush;
    this.hasMobilePush = contactsDto.hasMobilePush;
    this.lastSent = contactsDto.lastSent;
    this.lastSentDate = contactsDto.lastSentDate;
    this.lastOpen = contactsDto.lastOpen;
    this.lastOpenDate = contactsDto.lastOpenDate;
    this.lastClick = contactsDto.lastClick;
    this.lastClickDate = contactsDto.lastClickDate;
    this.lastAutomation = contactsDto.lastAutomation;
    this.lastAutomationDate = contactsDto.lastAutomationDate;
    this.sendingLimit = contactsDto.sendingLimit;
    this.customFields = contactsDto.customFields;
    this.score = contactsDto.score;
    this.scoreForecast = contactsDto.scoreForecast;
    this.createdAt = contactsDto.createdAt;
    this.updatedAt = contactsDto.updatedAt;
    this.webPushLastSent = contactsDto.webPushLastSent;
    this.webPushLastClick = contactsDto.webPushLastClick;
    this.webPushLastOpen = contactsDto.webPushLastOpen;
    this.webPushLastDelivered = contactsDto.webPushLastDelivered;
    this.mobPushLastClick = contactsDto.mobPushLastClick;
    this.mobPushLastSent = contactsDto.mobPushLastSent;
    this.mobPushLastOpen = contactsDto.mobPushLastOpen;
    this.mobPushLastDelivered = contactsDto.mobPushLastDelivered;
    this.smsLastSent = contactsDto.smsLastSent;
    this.smsLastClick = contactsDto.smsLastClick;
    this.smsLastOpen = contactsDto.smsLastOpen;
    this.smsLastDelivered = contactsDto.smsLastDelivered;
    this.whatsappLastClick = contactsDto.whatsappLastClick;
    this.whatsappLastSent = contactsDto.whatsappLastSent;
    this.whatsappLastOpen = contactsDto.whatsappLastOpen;
    this.whatsappLastDelivered = contactsDto.whatsappLastDelivered;
    this.contactTag = contactsDto.contactTag;
    this.postal = contactsDto.postal;
    this.city = contactsDto.city;
    this.region = contactsDto.region;
    this.country = contactsDto.country;
    this.webPush = contactsDto.webPush;
    this.isBlocked = contactsDto.isBlocked;
  }
}
