sonar.projectKey=brius_msgops-api
sonar.organization=brius
sonar.projectName=[BFM] Backend Api

sonar.links.homepage=https://gitlab.com/brius/bfm/msgops-api
sonar.links.ci=https://gitlab.com/brius/bfm/msgops-api/-/pipelines
sonar.links.scm=https://gitlab.com/brius/bfm/msgops-api/-/tree/staging/src
sonar.links.issue=https://gitlab.com/brius/bfm/msgops-api/-/issues

sonar.language=typescript

sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.tests=tests

sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
