version: '3.7'
services:
  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: ${TYPEORM_DATABASE}
      MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
    ports:
      - ${TYPEORM_PORT}:3306
    expose:
      - ${TYPEORM_PORT}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1.sql
      - my-db:/var/lib/mysql
    networks:
      - fullstack
  php-my-admin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - fullstack
    depends_on:
      - db
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      IDP_ISSUER: '${IDP_ISSUER}'
      IDP_AUDIENCE: '${IDP_AUDIENCE}'
      JWKS_PATH: '${JWKS_PATH}'
      IDP_SCOPE: '${IDP_SCOPE}'
      ALLOWED_ORIGIN: '${ALLOWED_ORIGIN}'
      SERVER_PORT: '${SERVER_PORT}'
      API_DOCS: '${API_DOCS}'
      API_PREFIX: '${API_PREFIX}'
      TYPEORM_HOST: db
      TYPEORM_USERNAME: '${TYPEORM_USERNAME}'
      TYPEORM_PORT: '${TYPEORM_PORT}'
      TYPEORM_PASSWORD: '${TYPEORM_PASSWORD}'
      TYPEORM_DATABASE: '${TYPEORM_DATABASE}'
      TYPEORM_CONNECTION: '${TYPEORM_CONNECTION}'
      TYPEORM_DRIVER_EXTRA: '${TYPEORM_DRIVER_EXTRA}'
      TYPEORM_ENTITIES_DIR: dist/entities/*.js
      TYPEORM_ENTITIES: dist/entities/*.js
      TYPEORM_MIGRATIONS_DIR: dist/migrations
      TYPEORM_MIGRATIONS: dist/migrations/*.js
      TYPEORM_MIGRATIONS_TABLE_NAME: '${TYPEORM_MIGRATIONS_TABLE_NAME}'
      TYPEORM_MIGRATIONS_RUN: '${TYPEORM_MIGRATIONS_RUN}'
      TYPEORM_DROP_SCHEMA: '${TYPEORM_DROP_SCHEMA}'
      GLOCK_API_KEY: '${GLOCK_API_KEY}'
      BUCKET_NAME: '${BUCKET_NAME}'
      SERVICE_ACCOUNT: '${SERVICE_ACCOUNT}'
      ONGAGE_USERNAME: '${ONGAGE_USERNAME}'
      ONGAGE_PASSWORD: '${ONGAGE_PASSWORD}'
      ONGAGE_ACCOUNT_CODE: '${ONGAGE_ACCOUNT_CODE}'
    expose:
      - ${SERVER_PORT}
    networks:
      - fullstack
    depends_on:
      - db
volumes:
  my-db:
networks:
  fullstack:
