info:
  name: Batch Automations
  type: http
  seq: 4

http:
  method: POST
  url: "{{send-email-url}}/batch/automations"
  body:
    type: json
    json: |
      {
        "automationId": 1,
        "contacts": [1, 2, 3]
      }
  auth: none

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
