stages:
  - build
  - deploy

build_staging:
  image: node:18
  stage: build
  environment:
    name: staging
  script:
    - export VITE_API_MSGOPS=$VUE_APP_API_URL
    - export VITE_AUTH0_DOMAIN=$AUTH0_DOMAIN
    - export VITE_AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
    - export VITE_AUTH0_AUDIENCE=$AUTH0_AUDIENCE
    - export VITE_AUTH0_CALLBACK_URL=$AUTH0_CALLBACK_URL
    - export VITE_APP_REDIRECT_MSGOPS=$VUE_APP_REDIRECT_MSGOPS
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist/
  only:
    - staging

build_production:
  image: node:18
  stage: build
  environment:
    name: production
  script:
    - export VITE_API_MSGOPS=$VUE_APP_API_URL
    - export VITE_AUTH0_DOMAIN=$AUTH0_DOMAIN
    - export VITE_AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
    - export VITE_AUTH0_AUDIENCE=$AUTH0_AUDIENCE
    - export VITE_AUTH0_CALLBACK_URL=$AUTH0_CALLBACK_URL
    - export VITE_APP_REDIRECT_MSGOPS=$VUE_APP_REDIRECT_MSGOPS
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist/
  only:
    - master
  when: manual

deploy_staging:
  stage: deploy
  environment:
    name: staging
  image: google/cloud-sdk:slim
  before_script:
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_KEY
    - gcloud config set project $GCP_PROJECT
  script:
    - gsutil -h "Cache-Control:no-cache,no-store,max-age=0" -m rsync -dr dist/ $GCP_BUCKET_NAME
  only:
    - staging

deploy_production:
  stage: deploy
  environment:
    name: production
  image: google/cloud-sdk:slim
  before_script:
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_KEY
    - gcloud config set project $GCP_PROJECT
  script:
    - gsutil -h "Cache-Control:no-cache,no-store,max-age=0" -m rsync -dr dist/ $GCP_BUCKET_NAME
  only:
    - master
  needs: ["build_production"]
