stages:
  - build
  - deploy
  - flushcache

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

build_staging:
  image: node:16
  stage: build
  environment:
    name: staging
  script:
    - export VUE_APP_API_URL=$VUE_APP_API_URL
    - export VUE_APP_AUTH0_DOMAIN=$VUE_APP_AUTH0_DOMAIN
    - export VUE_APP_AUTH0_CLIENT_ID=$VUE_APP_AUTH0_CLIENT_ID
    - export VUE_APP_AUTH0_AUDIENCE=$VUE_APP_AUTH0_AUDIENCE
    - export VUE_APP_REDIRECT_MANAGER=$VUE_APP_REDIRECT_MANAGER
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist/
  only:
    - staging
    - vue3-staging

build_production:
  image: node:16
  stage: build
  environment:
    name: production
  script:
    - export VUE_APP_API_URL=$VUE_APP_API_URL
    - export VUE_APP_AUTH0_DOMAIN=$VUE_APP_AUTH0_DOMAIN
    - export VUE_APP_AUTH0_CLIENT_ID=$VUE_APP_AUTH0_CLIENT_ID
    - export VUE_APP_AUTH0_AUDIENCE=$VUE_APP_AUTH0_AUDIENCE
    - export VUE_APP_REDIRECT_MANAGER=$VUE_APP_REDIRECT_MANAGER
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist/
  only:
    - master
  when: manual

build_vue3_production:
  image: node:16
  stage: build
  environment:
    name: production
  script:
    - export VUE_APP_API_URL=$VUE_APP_API_URL
    - export VUE_APP_AUTH0_DOMAIN=$VUE_APP_AUTH0_DOMAIN
    - export VUE_APP_AUTH0_CLIENT_ID=$VUE_APP_AUTH0_CLIENT_ID
    - export VUE_APP_AUTH0_AUDIENCE=$VUE_APP_AUTH0_AUDIENCE
    - export VUE_APP_REDIRECT_MANAGER=$VUE_APP_REDIRECT_MANAGER
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist/
  only:
    - vue3
  when: manual

deploy_staging:
  stage: deploy
  environment:
    name: staging
  image: google/cloud-sdk:slim
  before_script:
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_KEY
    - gcloud config set project $GCP_PROJECT
  script:
    - gsutil -h "Cache-Control:no-cache,no-store,max-age=0" -m rsync -dr dist/ $GCP_BUCKET_NAME
  only:
    - staging

deploy_vue3_staging:
  stage: deploy
  environment:
    name: staging
  image: google/cloud-sdk:slim
  before_script:
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_KEY
    - gcloud config set project $GCP_PROJECT
  script:
    - gsutil -h "Cache-Control:no-cache,no-store,max-age=0" -m rsync -dr dist/ $GCP_BUCKET_VUE3_NAME
  only:
    - vue3-staging

deploy_production:
  stage: deploy
  environment:
    name: production
  image: google/cloud-sdk:slim
  before_script:
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_KEY
    - gcloud config set project $GCP_PROJECT
  script:
    - gsutil -h "Cache-Control:no-cache,no-store,max-age=0" -m rsync -dr dist/ $GCP_BUCKET_NAME
  only:
    - master
  needs: ['build_production']

deploy_vue3_production:
  stage: deploy
  environment:
    name: production
  image: google/cloud-sdk:slim
  before_script:
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_KEY
    - gcloud config set project $GCP_PROJECT
  script:
    - gsutil -h "Cache-Control:no-cache,no-store,max-age=0" -m rsync -dr dist/ $GCP_BUCKET_VUE3_NAME
  only:
    - vue3
  needs: ['build_production']

flushcache_production:
  stage: flushcache
  environment:
    name: production
  image: docker:stable
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - |
      curl --fail --output "/dev/null" --silent --show-error -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache" \
      -H "Authorization: Bearer $CF_API_TOKEN" -H "Content-Type: application/json" \
      --data "{\"prefixes\": [\"$CF_PURGE_PREFIX\"]}"
  only:
    - master
  needs: ['deploy_production']
