services:
  frontend-vue2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend-vue2
    ports:
      - '44357:44357'
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./babel.config.js:/app/babel.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./postcss.config.js:/app/postcss.config.js
      - /app/node_modules
    stdin_open: true
    tty: true
