sonar.projectKey=etus-msgops-frontend
sonar.organization=etus
sonar.projectName=MsgOps Frontend
sonar.projectVersion=0.1
sonar.sourceEncoding=UTF-8
sonar.sources=./
sonar.exclusions=**/node_modules/**,**/**.scss,**/**.css,src/assets/**
