info:
  name: Cancel Automation
  type: http
  seq: 3

http:
  method: POST
  url: '{{tag-process-url}}/cancel'
  body:
    type: json
    json: |
      {
        "contactId": 1,
        "automationId": 1,
        "accountId": 1
      }
  auth: none

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
