import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { usePermissions } from '@/hooks/use-permissions';
import { useAccountId } from '../use-settings';
import { webPushGateway, type WebPushSettings } from './web-push-gateway';

// URL filters persist as newline-joined strings but edit as repeating inputs.
function splitUrls(v?: string): string[] {
  const list = (v ?? '')
    .split('\n')
    .map((x) => x.trim())
    .filter(Boolean);
  return list.length ? list : [''];
}
function joinUrls(list: string[]): string {
  return list.map((x) => x.trim()).filter(Boolean).join('\n');
}

// Enterprise-style web-push UI (single-project): Download SW.JS + autogenerated
// install snippet + opt-in popup builder + URL filters. NO Firebase/VAPID fields
// (those are platform-level, configured by super-admin in the FCM tab).
export function WebPushSection() {
  const { t } = useTranslation();
  const accountId = useAccountId();
  const qc = useQueryClient();
  const { can } = usePermissions();
  const canEdit = can('account:settings_update');

  const { data, isLoading } = useQuery({
    queryKey: ['settings', 'web-push-integration', accountId],
    queryFn: () => webPushGateway.getIntegration(accountId),
    enabled: accountId > 0,
  });

  const [s, setS] = useState<WebPushSettings>({ position: 'top', backgroundColor: '#FFFFFF', trigger: 'onload' });
  // URL filters are stored as newline-joined strings; edited as lists in the UI.
  const [showUrls, setShowUrls] = useState<string[]>(['']);
  const [hideUrls, setHideUrls] = useState<string[]>(['']);

  useEffect(() => {
    if (data?.settings) {
      setS((prev) => ({ ...prev, ...data.settings }));
      setShowUrls(splitUrls(data.settings.urlFilterShow));
      setHideUrls(splitUrls(data.settings.urlFilterHide));
    }
  }, [data]);

  const set = <K extends keyof WebPushSettings>(k: K, v: WebPushSettings[K]) => setS((p) => ({ ...p, [k]: v }));

  const save = useMutation({
    mutationFn: () =>
      webPushGateway.saveSettings(accountId, {
        ...s,
        urlFilterShow: joinUrls(showUrls),
        urlFilterHide: joinUrls(hideUrls),
      }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['settings', 'web-push-integration', accountId] });
      toast.success(t('settings.webPushSaved') ?? 'Configuração de web-push salva.');
    },
    onError: (e: any) => toast.error(e?.response?.data?.message ?? 'Erro ao salvar.'),
  });

  const regen = useMutation({
    mutationFn: () => webPushGateway.regenerateSw(accountId),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['settings', 'web-push-integration', accountId] });
      toast.success(t('settings.webPushSwRegenerated') ?? 'Service worker regenerado.');
    },
    onError: (e: any) => toast.error(e?.response?.data?.message ?? 'Erro ao regenerar.'),
  });

  function copySnippet() {
    if (!data?.snippet) return;
    navigator.clipboard.writeText(data.snippet).then(
      () => toast.success(t('common.copied') ?? 'Copiado.'),
      () => toast.error('Erro ao copiar.'),
    );
  }

  // Downloads the tiny same-origin sw.js the customer hosts at their site root.
  // It just importScripts the BMS-served worker (importScripts is cross-origin),
  // so service-worker registration stays same-origin on the customer side.
  function downloadSw() {
    if (!data?.serviceWorkerUrl) return;
    const content = `// BMS Web-Push service worker — host this file at your site root as /sw.js\nimportScripts("${data.serviceWorkerUrl}");\n`;
    const blob = new Blob([content], { type: 'application/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'sw.js';
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  if (isLoading) return <p className="text-muted-foreground mt-8 text-sm">{t('common.loading') ?? 'Carregando...'}</p>;

  return (
    <div className="mt-4 flex max-w-3xl flex-col gap-8">
      {/* 1. Integração — Download SW + snippet */}
      <section className="flex flex-col gap-3">
        <h3 className="text-lg font-medium">{t('settings.webPushIntegrationTitle') ?? 'Integração — Push Notification'}</h3>
        <p className="text-muted-foreground text-sm">{t('settings.webPushIntegrationHelp') ?? 'Para configurar push em um site, siga os 2 passos:'}</p>

        <div className="flex flex-col gap-1.5">
          <span className="text-sm">1. {t('settings.webPushStep1') ?? 'Baixe o sw.js e salve na raiz do site/domínio.'}</span>
          <div className="flex gap-2">
            <Button type="button" variant="default" size="sm" onClick={downloadSw} disabled={!data?.serviceWorkerUrl}>
              {t('settings.downloadSw') ?? 'Download SW.JS'}
            </Button>
            <Button type="button" variant="outline" size="sm" onClick={() => regen.mutate()} disabled={!canEdit || regen.isPending}>
              {regen.isPending ? '...' : (t('settings.regenerateSw') ?? 'Regenerar')}
            </Button>
          </div>
        </div>

        <div className="flex flex-col gap-1.5">
          <div className="flex items-center justify-between">
            <span className="text-sm">2. {t('settings.webPushStep2') ?? 'Cole este código no <head> do site.'}</span>
            <Button type="button" variant="outline" size="sm" onClick={copySnippet}>
              {t('common.copy') ?? 'Copiar'}
            </Button>
          </div>
          <Textarea readOnly rows={12} className="font-mono text-xs" value={data?.snippet ?? ''} />
        </div>
      </section>

      {/* 2. Opt-in popup builder + preview */}
      <section className="flex flex-col gap-3">
        <h3 className="text-lg font-medium">{t('settings.optinTitle') ?? 'Opt-in Pop-up'}</h3>
        <label className="flex items-center gap-2 text-sm">
          <input type="checkbox" checked={Boolean(s.isActive)} onChange={(e) => set('isActive', e.target.checked)} disabled={!canEdit} />
          {t('settings.webPushActive') ?? 'Web-push ativo nesta conta'}
        </label>

        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          {/* preview — a mocked website page with the opt-in popup placed per the
              selected Position (top/center/bottom), like the Enterprise UI. */}
          <div
            className="relative overflow-hidden rounded-md bg-gray-100 p-3"
            style={{ minHeight: 300, justifyContent: s.position === 'bottom' ? 'flex-end' : s.position === 'center' ? 'center' : 'flex-start', display: 'flex', flexDirection: 'column' }}
          >
            {/* faux page skeleton behind the popup */}
            <div className="pointer-events-none absolute inset-3 flex flex-col gap-3 opacity-60">
              <div className="h-24 rounded bg-gray-300" />
              <div className="flex gap-3">
                <div className="h-40 w-1/3 rounded bg-gray-300" />
                <div className="flex flex-1 flex-col gap-2">
                  <div className="h-8 rounded bg-gray-300" />
                  <div className="h-8 rounded bg-gray-300" />
                  <div className="h-8 rounded bg-gray-300" />
                </div>
              </div>
            </div>
            {/* the opt-in popup */}
            <div className="relative z-10 mx-auto w-full max-w-md rounded-md border bg-white p-3 shadow-lg" style={{ backgroundColor: s.backgroundColor || '#FFFFFF' }}>
              <div className="flex gap-3">
                <div className="h-12 w-12 flex-shrink-0 rounded bg-gray-200" />
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-semibold text-black">{s.optinTitle || (t('settings.optinTitlePlaceholder') ?? 'Título do opt-in')}</p>
                  <p className="text-xs text-gray-600">{s.optinBody || 'Lorem ipsum dolor sit amet consectetur. Nunc nibh ut purus diam.'}</p>
                </div>
              </div>
              <div className="mt-3 flex justify-end gap-2">
                <span className="rounded bg-gray-200 px-3 py-1 text-xs text-gray-600">{s.optinDenyLabel || (t('settings.optinDeny') ?? 'Não')}</span>
                <span className="rounded bg-green-500 px-3 py-1 text-xs text-white">{s.optinAllowLabel || (t('settings.optinAllow') ?? 'Permitir')}</span>
              </div>
            </div>
          </div>

          {/* fields */}
          <div className="flex flex-col gap-3">
            <div className="flex flex-col gap-1">
              <Label htmlFor="op-title">{t('settings.optinTitleField') ?? 'Título'}</Label>
              <Input id="op-title" value={s.optinTitle ?? ''} onChange={(e) => set('optinTitle', e.target.value)} disabled={!canEdit} />
            </div>
            <div className="flex flex-col gap-1">
              <Label htmlFor="op-body">{t('settings.optinBodyField') ?? 'Mensagem'}</Label>
              <Textarea id="op-body" rows={2} value={s.optinBody ?? ''} onChange={(e) => set('optinBody', e.target.value)} disabled={!canEdit} />
            </div>
            <div className="grid grid-cols-2 gap-2">
              <div className="flex flex-col gap-1">
                <Label htmlFor="op-pos">{t('settings.position') ?? 'Posição'}</Label>
                <select id="op-pos" className="h-9 rounded-md border bg-background px-2 text-sm" value={s.position ?? 'top'} onChange={(e) => set('position', e.target.value as WebPushSettings['position'])} disabled={!canEdit}>
                  <option value="top">{t('settings.posTop') ?? 'Topo'}</option>
                  <option value="center">{t('settings.posCenter') ?? 'Centro'}</option>
                  <option value="bottom">{t('settings.posBottom') ?? 'Rodapé'}</option>
                </select>
              </div>
              <div className="flex flex-col gap-1">
                <Label htmlFor="op-bg">{t('settings.bgColor') ?? 'Cor do fundo'}</Label>
                <Input id="op-bg" type="text" value={s.backgroundColor ?? '#FFFFFF'} onChange={(e) => set('backgroundColor', e.target.value)} disabled={!canEdit} />
              </div>
            </div>

            <fieldset className="flex flex-col gap-2">
              <legend className="text-sm font-medium">{t('settings.trigger') ?? 'Trigger'}</legend>
              {(['onload', 'delay', 'scroll', 'inactivity'] as const).map((tr) => (
                <label key={tr} className="flex items-center gap-2 text-sm">
                  <input type="radio" name="trigger" checked={(s.trigger ?? 'onload') === tr} onChange={() => set('trigger', tr)} disabled={!canEdit} />
                  {tr === 'onload' && (t('settings.triggerOnload') ?? 'No acesso')}
                  {tr === 'delay' && (t('settings.triggerDelay') ?? 'Após N segundos')}
                  {tr === 'scroll' && (t('settings.triggerScroll') ?? 'Por % de rolagem')}
                  {tr === 'inactivity' && (t('settings.triggerInactivity') ?? 'Por inatividade')}
                </label>
              ))}
              {s.trigger === 'delay' && (
                <Input type="number" min={0} value={s.triggerDelaySeconds ?? 0} onChange={(e) => set('triggerDelaySeconds', Number(e.target.value))} disabled={!canEdit} className="w-24" />
              )}
              {s.trigger === 'scroll' && (
                <Input type="number" min={0} max={100} value={s.triggerScrollPercent ?? 0} onChange={(e) => set('triggerScrollPercent', Number(e.target.value))} disabled={!canEdit} className="w-24" />
              )}
              {s.trigger === 'inactivity' && (
                <Input type="number" min={0} value={s.triggerInactivitySeconds ?? 0} onChange={(e) => set('triggerInactivitySeconds', Number(e.target.value))} disabled={!canEdit} className="w-24" />
              )}
            </fieldset>
          </div>
        </div>
      </section>

      {/* 3. URL filters — repeating "+ Add URL" lists (Enterprise-style) */}
      <section className="flex flex-col gap-4">
        <UrlListField label={t('settings.showOn') ?? 'Exibir em'} addLabel={t('settings.addUrl') ?? 'Adicionar URL'} urls={showUrls} setUrls={setShowUrls} disabled={!canEdit} />
        <UrlListField label={t('settings.hideOn') ?? 'Não exibir em'} addLabel={t('settings.addUrl') ?? 'Adicionar URL'} urls={hideUrls} setUrls={setHideUrls} disabled={!canEdit} />
        <p className="text-muted-foreground text-xs">{t('settings.urlFilterHint') ?? 'Use o asterisco (*) no início, meio ou fim para exibir/ocultar em qualquer URL. Ex: *utm_source=google*, *quiz*'}</p>
      </section>

      <div>
        <Button type="button" onClick={() => save.mutate()} disabled={!canEdit || save.isPending}>
          {save.isPending ? '...' : (t('common.save') ?? 'Salvar')}
        </Button>
      </div>
    </div>
  );
}

// Repeating URL input list with "+ Add URL" / remove (Enterprise-style).
function UrlListField({ label, addLabel, urls, setUrls, disabled }: { label: string; addLabel: string; urls: string[]; setUrls: (v: string[]) => void; disabled?: boolean }) {
  const update = (i: number, v: string) => setUrls(urls.map((u, idx) => (idx === i ? v : u)));
  const add = () => setUrls([...urls, '']);
  const remove = (i: number) => setUrls(urls.length > 1 ? urls.filter((_, idx) => idx !== i) : ['']);
  return (
    <div className="flex flex-col gap-2">
      <Label>{label}</Label>
      {urls.map((u, i) => (
        <div key={i} className="flex items-center gap-2">
          <Input placeholder="https://exemplo.com/* " value={u} onChange={(e) => update(i, e.target.value)} disabled={disabled} className="font-mono text-xs" />
          <Button type="button" variant="ghost" size="icon" onClick={() => remove(i)} disabled={disabled} aria-label="remover">
            ✕
          </Button>
        </div>
      ))}
      <div>
        <Button type="button" variant="outline" size="sm" onClick={add} disabled={disabled}>
          + {addLabel}
        </Button>
      </div>
    </div>
  );
}
