
POST https://your-lead-conception.example.com/workflow?preview=true
content-type: application/json

{
  "contact": {
    "email": "contact@example.com",
    "phone": "5511999999999",
    "hashedEmail": "03cd5f4df96fb9ee12c8ffd4d2185961a0ec34a510ba7708c86d1b7604c46b27",
    "firstName": "Example",
    "lastName": "Contact",
    "audienceName": "test_audience",
    "audienceUrl": "test_audience"
  },
  "listId": "test_audience",
  "startDate": 1644608497893
}
